import type { Country } from './types';

export const COUNTRIES: Country[] = [
    { name: "Afghanistan", emoji: "🇦🇫" },
    { name: "Albania", emoji: "🇦🇱" },
    { name: "Algeria", emoji: "🇩🇿" },
    { name: "Argentina", emoji: "🇦🇷" },
    { name: "Australia", emoji: "🇦🇺" },
    { name: "Austria", emoji: "🇦🇹" },
    { name: "Bangladesh", emoji: "🇧🇩" },
    { name: "Belgium", emoji: "🇧🇪" },
    { name: "Brazil", emoji: "🇧🇷" },
    { name: "Canada", emoji: "🇨🇦" },
    { name: "China", emoji: "🇨🇳" },
    { name: "Colombia", emoji: "🇨🇴" },
    { name: "Congo", emoji: "🇨🇬" },
    { name: "Cuba", emoji: "🇨🇺" },
    { name: "Denmark", emoji: "🇩🇰" },
    { name: "Egypt", emoji: "🇪🇬" },
    { name: "Ethiopia", emoji: "🇪🇹" },
    { name: "Finland", emoji: "🇫🇮" },
    { name: "France", emoji: "🇫🇷" },
    { name: "Germany", emoji: "🇩🇪" },
    { name: "Ghana", emoji: "🇬🇭" },
    { name: "Greece", emoji: "🇬🇷" },
    { name: "India", emoji: "🇮🇳" },
    { name: "Indonesia", emoji: "🇮🇩" },
    { name: "Iran", emoji: "🇮🇷" },
    { name: "Iraq", emoji: "🇮🇶" },
    { name: "Ireland", emoji: "🇮🇪" },
    { name: "Israel", emoji: "🇮🇱" },
    { name: "Italy", emoji: "🇮🇹" },
    { name: "Jamaica", emoji: "🇯🇲" },
    { name: "Japan", emoji: "🇯🇵" },
    { name: "Kenya", emoji: "🇰🇪" },
    { name: "Mexico", emoji: "🇲🇽" },
    { name: "Morocco", emoji: "🇲🇦" },
    { name: "Nepal", emoji: "🇳🇵" },
    { name: "Netherlands", emoji: "🇳🇱" },
    { name: "New Zealand", emoji: "🇳🇿" },
    { name: "Nigeria", emoji: "🇳🇬" },
    { name: "North Korea", emoji: "🇰🇵" },
    { name: "Norway", emoji: "🇳🇴" },
    { name: "Pakistan", emoji: "🇵🇰" },
    { name: "Peru", emoji: "🇵🇪" },
    { name: "Philippines", emoji: "🇵🇭" },
    { name: "Poland", emoji: "🇵🇱" },
    { name: "Portugal", emoji: "🇵🇹" },
    { name: "Russia", emoji: "🇷🇺" },
    { name: "Saudi Arabia", emoji: "🇸🇦" },
    { name: "South Africa", emoji: "🇿🇦" },
    { name: "South Korea", emoji: "🇰🇷" },
    { name: "Spain", emoji: "🇪🇸" },
    { name: "Sweden", emoji: "🇸🇪" },
    { name: "Switzerland", emoji: "🇨🇭" },
    { name: "Syria", emoji: "🇸🇾" },
    { name: "Thailand", emoji: "🇹🇭" },
    { name: "Turkey", emoji: "🇹🇷" },
    { name: "Uganda", emoji: "🇺🇬" },
    { name: "Ukraine", emoji: "🇺🇦" },
    { name: "United Arab Emirates", emoji: "🇦🇪" },
    { name: "United Kingdom", emoji: "🇬🇧" },
    { name: "United States", emoji: "🇺🇸" },
    { name: "Vietnam", emoji: "🇻🇳" },
    { name: "Zimbabwe", emoji: "🇿🇼" }
];

export const DEFAULT_TARGET_COUNTRIES: string[] = ["United States", "Japan", "Nigeria", "Brazil"];